#!/usr/bin/env python3
"""
Semantic Boost Cache - Persist and load Claude's semantic analysis results.

This module provides a caching layer for semantic boost scores generated by
Claude's LLM analysis. It bridges the gap between Claude's analysis output
and the schedule generation pipeline.

The workflow:
1. Claude analyzes captions and determines persona boosts (1.0-1.4x)
2. Claude saves results to a JSON file via SemanticBoostCache.save()
3. generate_schedule.py loads results via SemanticBoostCache.load()
4. Pipeline applies semantic boosts in Step 3 (MATCH PERSONA)

Cache Location:
    ~/.eros/schedules/semantic/{creator_name}/{week}_semantic.json

    Alternative (configurable via EROS_SEMANTIC_CACHE_PATH):
    {EROS_SEMANTIC_CACHE_PATH}/{creator_name}/{week}_semantic.json

JSON Format:
    {
        "creator_name": "grace_bennett",
        "week": "2025-W50",
        "generated_at": "2025-12-10T14:30:00",
        "semantic_results": [
            {
                "caption_id": 12345,
                "detected_tone": "bratty",
                "persona_boost": 1.25,
                "quality_score": 0.80,
                "reasoning": "Strong bratty undertones with playful hook"
            }
        ]
    }

Usage:
    from semantic_boost_cache import SemanticBoostCache

    # Save Claude's analysis
    cache = SemanticBoostCache()
    cache.save("grace_bennett", "2025-W50", semantic_results)

    # Load for pipeline
    boosts = cache.load("grace_bennett", "2025-W50")

    # Or auto-discover latest for creator
    boosts = cache.load_latest("grace_bennett")
"""

from __future__ import annotations

import json
import logging
import os
from dataclasses import asdict, dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

from models import SemanticBoostResult

logger = logging.getLogger(__name__)

# Default cache location
HOME_DIR = Path.home()
DEFAULT_CACHE_DIR = Path(
    os.environ.get(
        "EROS_SEMANTIC_CACHE_PATH",
        str(HOME_DIR / ".eros" / "schedules" / "semantic"),
    )
)


@dataclass
class SemanticCacheEntry:
    """
    A single semantic analysis entry in the cache.

    This is the format Claude should use when saving analysis results.
    It maps directly to SemanticBoostResult for pipeline consumption.

    Attributes:
        caption_id: The caption ID this analysis applies to.
        detected_tone: Claude's detected tone (playful, bratty, etc.).
        persona_boost: The calculated persona boost (1.0-1.4).
        quality_score: Content quality score (0.0-1.0).
        reasoning: Brief explanation of the analysis.
        tone_confidence: Confidence in tone detection (0.0-1.0).
        emoji_alignment: Emoji alignment level (perfect, good, moderate, poor).
        slang_alignment: Slang alignment level (perfect, good, moderate, poor).
    """

    caption_id: int
    detected_tone: str
    persona_boost: float
    quality_score: float = 0.0
    reasoning: str = ""
    tone_confidence: float = 0.0
    emoji_alignment: str = "good"
    slang_alignment: str = "good"

    def to_semantic_boost_result(self) -> SemanticBoostResult:
        """Convert cache entry to SemanticBoostResult for pipeline."""
        return SemanticBoostResult(
            caption_id=self.caption_id,
            persona_boost=self.persona_boost,
            detected_tone=self.detected_tone,
            tone_confidence=self.tone_confidence,
            matches_creator_voice=self.persona_boost >= 1.1,
            emoji_alignment=self.emoji_alignment,
            slang_alignment=self.slang_alignment,
            authenticity_score=self.quality_score,
            reasoning=self.reasoning,
        )


class SemanticBoostCache:
    """
    Cache manager for semantic boost scores.

    Provides methods to save and load Claude's semantic analysis results
    as JSON files. The cache is organized by creator and week.

    Attributes:
        cache_dir: Root directory for semantic cache files.

    Example:
        >>> cache = SemanticBoostCache()
        >>>
        >>> # Save analysis results
        >>> results = [
        ...     {"caption_id": 123, "detected_tone": "bratty", "persona_boost": 1.25},
        ...     {"caption_id": 456, "detected_tone": "playful", "persona_boost": 1.15},
        ... ]
        >>> cache.save("grace_bennett", "2025-W50", results)
        >>>
        >>> # Load for pipeline
        >>> boosts = cache.load("grace_bennett", "2025-W50")
        >>> print(boosts[123].persona_boost)
        1.25
    """

    def __init__(self, cache_dir: Path | str | None = None):
        """
        Initialize the semantic boost cache.

        Args:
            cache_dir: Root directory for cache files. Defaults to
                ~/.eros/schedules/semantic or EROS_SEMANTIC_CACHE_PATH.
        """
        if cache_dir is None:
            self.cache_dir = DEFAULT_CACHE_DIR
        else:
            self.cache_dir = Path(cache_dir)

    def get_cache_path(self, creator_name: str, week: str) -> Path:
        """
        Get the cache file path for a creator and week.

        Args:
            creator_name: Creator's page name (e.g., "grace_bennett").
            week: ISO week string (e.g., "2025-W50").

        Returns:
            Path to the cache JSON file.
        """
        # Sanitize creator name for safe filesystem usage
        safe_name = creator_name.lower().replace(" ", "_")
        return self.cache_dir / safe_name / f"{week}_semantic.json"

    def get_creator_cache_dir(self, creator_name: str) -> Path:
        """Get the cache directory for a specific creator."""
        safe_name = creator_name.lower().replace(" ", "_")
        return self.cache_dir / safe_name

    def exists(self, creator_name: str, week: str) -> bool:
        """
        Check if a cache file exists for the given creator and week.

        Args:
            creator_name: Creator's page name.
            week: ISO week string.

        Returns:
            True if cache file exists, False otherwise.
        """
        return self.get_cache_path(creator_name, week).exists()

    def save(
        self,
        creator_name: str,
        week: str,
        results: list[dict[str, Any]] | list[SemanticCacheEntry],
        generated_at: datetime | None = None,
    ) -> Path:
        """
        Save semantic analysis results to cache.

        Args:
            creator_name: Creator's page name.
            week: ISO week string (e.g., "2025-W50").
            results: List of semantic analysis results. Each result should have
                at minimum: caption_id, detected_tone, persona_boost.
            generated_at: Timestamp of generation. Defaults to now.

        Returns:
            Path to the saved cache file.

        Raises:
            ValueError: If results are missing required fields.

        Example:
            >>> cache.save("grace_bennett", "2025-W50", [
            ...     {"caption_id": 123, "detected_tone": "bratty", "persona_boost": 1.25},
            ... ])
        """
        if generated_at is None:
            generated_at = datetime.now()

        # Convert SemanticCacheEntry objects to dicts if needed
        results_dicts = []
        for result in results:
            if isinstance(result, SemanticCacheEntry):
                results_dicts.append(asdict(result))
            elif isinstance(result, dict):
                # Validate required fields
                if "caption_id" not in result:
                    raise ValueError("Each result must have 'caption_id'")
                if "persona_boost" not in result:
                    raise ValueError("Each result must have 'persona_boost'")
                results_dicts.append(result)
            else:
                raise ValueError(f"Unexpected result type: {type(result)}")

        cache_data = {
            "creator_name": creator_name,
            "week": week,
            "generated_at": generated_at.isoformat(),
            "semantic_results": results_dicts,
            "version": "1.0",
            "result_count": len(results_dicts),
        }

        cache_path = self.get_cache_path(creator_name, week)
        cache_path.parent.mkdir(parents=True, exist_ok=True)
        cache_path.write_text(json.dumps(cache_data, indent=2))

        logger.info(
            f"Saved {len(results_dicts)} semantic boost results to {cache_path}"
        )
        return cache_path

    def load(
        self,
        creator_name: str,
        week: str,
    ) -> dict[int, SemanticBoostResult]:
        """
        Load semantic boost results from cache.

        Args:
            creator_name: Creator's page name.
            week: ISO week string.

        Returns:
            Dictionary mapping caption_id to SemanticBoostResult.
            Empty dict if cache file doesn't exist.

        Raises:
            json.JSONDecodeError: If cache file is invalid JSON.
        """
        cache_path = self.get_cache_path(creator_name, week)

        if not cache_path.exists():
            logger.debug(f"No semantic cache found at {cache_path}")
            return {}

        content = cache_path.read_text()
        data = json.loads(content)

        results: dict[int, SemanticBoostResult] = {}

        # Handle both "semantic_results" and "captions" array formats
        items = data.get("semantic_results", []) or data.get("captions", [])
        for item in items:
            if "caption_id" not in item:
                logger.warning("Skipping cache entry without caption_id")
                continue
            if "persona_boost" not in item:
                logger.warning(f"Skipping caption {item['caption_id']}: missing persona_boost")
                continue

            caption_id = int(item["caption_id"])

            results[caption_id] = SemanticBoostResult(
                caption_id=caption_id,
                persona_boost=float(item["persona_boost"]),
                detected_tone=item.get("detected_tone", "unknown"),
                tone_confidence=float(item.get("tone_confidence", 0.0)),
                matches_creator_voice=item.get("matches_creator_voice", True),
                emoji_alignment=item.get("emoji_alignment", "good"),
                slang_alignment=item.get("slang_alignment", "good"),
                authenticity_score=float(item.get("quality_score", 0.0)),
                reasoning=item.get("reasoning", ""),
            )

        logger.info(
            f"Loaded {len(results)} semantic boost results from {cache_path}"
        )
        return results

    def load_latest(
        self,
        creator_name: str,
        max_age_weeks: int = 4,
    ) -> tuple[dict[int, SemanticBoostResult], str | None]:
        """
        Load the most recent semantic cache for a creator.

        Searches for cache files in the creator's directory and returns
        the most recent one within the age limit.

        Args:
            creator_name: Creator's page name.
            max_age_weeks: Maximum age of cache to consider (default 4 weeks).

        Returns:
            Tuple of (results dict, week string or None if no cache found).
        """
        creator_dir = self.get_creator_cache_dir(creator_name)

        if not creator_dir.exists():
            logger.debug(f"No semantic cache directory for {creator_name}")
            return {}, None

        # Find all semantic cache files
        cache_files = list(creator_dir.glob("*_semantic.json"))

        if not cache_files:
            logger.debug(f"No semantic cache files in {creator_dir}")
            return {}, None

        # Sort by modification time (most recent first)
        cache_files.sort(key=lambda p: p.stat().st_mtime, reverse=True)

        # Try to load the most recent one
        for cache_file in cache_files:
            # Extract week from filename
            week = cache_file.stem.replace("_semantic", "")

            try:
                results = self.load(creator_name, week)
                if results:
                    logger.info(
                        f"Loaded latest semantic cache for {creator_name}: "
                        f"{week} ({len(results)} results)"
                    )
                    return results, week
            except Exception as e:
                logger.warning(f"Failed to load cache {cache_file}: {e}")
                continue

        return {}, None

    def list_cached_weeks(self, creator_name: str) -> list[str]:
        """
        List all cached weeks for a creator.

        Args:
            creator_name: Creator's page name.

        Returns:
            List of week strings (e.g., ["2025-W49", "2025-W50"]).
        """
        creator_dir = self.get_creator_cache_dir(creator_name)

        if not creator_dir.exists():
            return []

        weeks = []
        for cache_file in creator_dir.glob("*_semantic.json"):
            week = cache_file.stem.replace("_semantic", "")
            weeks.append(week)

        return sorted(weeks)

    def get_cache_stats(self, creator_name: str, week: str) -> dict[str, Any]:
        """
        Get statistics about a cached semantic analysis.

        Args:
            creator_name: Creator's page name.
            week: ISO week string.

        Returns:
            Dictionary with cache statistics.
        """
        cache_path = self.get_cache_path(creator_name, week)

        if not cache_path.exists():
            return {"exists": False}

        content = cache_path.read_text()
        data = json.loads(content)

        # Handle both "semantic_results" and "captions" array formats
        results = data.get("semantic_results", []) or data.get("captions", [])
        boosts = [r.get("persona_boost", 1.0) for r in results]

        return {
            "exists": True,
            "path": str(cache_path),
            "generated_at": data.get("generated_at") or data.get("analyzed_at"),
            "result_count": len(results),
            "avg_boost": sum(boosts) / len(boosts) if boosts else 0,
            "min_boost": min(boosts) if boosts else 0,
            "max_boost": max(boosts) if boosts else 0,
            "boost_coverage": sum(1 for b in boosts if b > 1.0) / len(boosts) * 100 if boosts else 0,
        }

    def clear(self, creator_name: str, week: str) -> bool:
        """
        Delete a cached semantic analysis.

        Args:
            creator_name: Creator's page name.
            week: ISO week string.

        Returns:
            True if cache was deleted, False if it didn't exist.
        """
        cache_path = self.get_cache_path(creator_name, week)

        if cache_path.exists():
            cache_path.unlink()
            logger.info(f"Deleted semantic cache: {cache_path}")
            return True

        return False


def create_semantic_results_from_analysis(
    analysis_output: list[dict[str, Any]],
) -> list[SemanticCacheEntry]:
    """
    Convert Claude's analysis output to SemanticCacheEntry objects.

    This helper function transforms Claude's raw analysis output into
    the structured format expected by the cache.

    Args:
        analysis_output: List of dicts from Claude's analysis, typically:
            {
                "caption_id": 123,
                "detected_tone": "bratty",
                "persona_match": 0.85,
                "quality_score": 0.75,
                "reasoning": "Strong bratty undertones..."
            }

    Returns:
        List of SemanticCacheEntry objects ready for caching.
    """
    entries = []

    for item in analysis_output:
        caption_id = item.get("caption_id")
        if caption_id is None:
            continue

        # Handle different field names Claude might use
        persona_boost = item.get("persona_boost") or item.get("recommended_boost") or 1.0

        # Convert persona_match (0-1) to persona_boost (1.0-1.4) if needed
        if "persona_match" in item and "persona_boost" not in item:
            persona_match = float(item["persona_match"])
            # Scale persona_match (0-1) to boost (1.0-1.4)
            persona_boost = 1.0 + (persona_match * 0.4)

        entries.append(
            SemanticCacheEntry(
                caption_id=int(caption_id),
                detected_tone=item.get("detected_tone", item.get("true_tone", "unknown")),
                persona_boost=float(persona_boost),
                quality_score=float(item.get("quality_score", 0.0)),
                reasoning=item.get("reasoning", item.get("notes", "")),
                tone_confidence=float(item.get("confidence", item.get("tone_confidence", 0.0))),
            )
        )

    return entries


# =============================================================================
# CLI for testing and manual cache management
# =============================================================================


def main():
    """CLI entry point for cache management."""
    import argparse

    parser = argparse.ArgumentParser(
        description="Manage semantic boost cache files.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    # Check if cache exists
    python semantic_boost_cache.py --creator grace_bennett --week 2025-W50 --check

    # Show cache stats
    python semantic_boost_cache.py --creator grace_bennett --week 2025-W50 --stats

    # List all cached weeks for a creator
    python semantic_boost_cache.py --creator grace_bennett --list

    # Load and display cache contents
    python semantic_boost_cache.py --creator grace_bennett --week 2025-W50 --show
        """,
    )

    parser.add_argument("--creator", "-c", required=True, help="Creator page name")
    parser.add_argument("--week", "-w", help="Week in ISO format (YYYY-Www)")
    parser.add_argument("--check", action="store_true", help="Check if cache exists")
    parser.add_argument("--stats", action="store_true", help="Show cache statistics")
    parser.add_argument("--list", action="store_true", help="List all cached weeks")
    parser.add_argument("--show", action="store_true", help="Display cache contents")
    parser.add_argument("--clear", action="store_true", help="Delete cache file")
    parser.add_argument("--cache-dir", help="Override cache directory")

    args = parser.parse_args()

    cache = SemanticBoostCache(args.cache_dir)

    if args.list:
        weeks = cache.list_cached_weeks(args.creator)
        if weeks:
            print(f"Cached weeks for {args.creator}:")
            for week in weeks:
                print(f"  - {week}")
        else:
            print(f"No cached semantic analysis for {args.creator}")
        return

    if not args.week:
        parser.error("--week is required for this operation")

    if args.check:
        exists = cache.exists(args.creator, args.week)
        if exists:
            print(f"Cache exists: {cache.get_cache_path(args.creator, args.week)}")
        else:
            print("Cache does not exist")
        return

    if args.stats:
        stats = cache.get_cache_stats(args.creator, args.week)
        if stats["exists"]:
            print(f"Semantic Cache Statistics for {args.creator} / {args.week}")
            print("-" * 50)
            print(f"  Path: {stats['path']}")
            print(f"  Generated: {stats['generated_at']}")
            print(f"  Results: {stats['result_count']}")
            print(f"  Avg Boost: {stats['avg_boost']:.2f}x")
            print(f"  Min Boost: {stats['min_boost']:.2f}x")
            print(f"  Max Boost: {stats['max_boost']:.2f}x")
            print(f"  Boost Coverage: {stats['boost_coverage']:.1f}%")
        else:
            print("Cache does not exist")
        return

    if args.show:
        boosts = cache.load(args.creator, args.week)
        if boosts:
            print(f"Semantic Boost Results for {args.creator} / {args.week}")
            print("-" * 70)
            print(f"{'Caption ID':<12} {'Tone':<12} {'Boost':<8} {'Confidence':<12} Reasoning")
            print("-" * 70)
            for caption_id, result in sorted(boosts.items()):
                reasoning = result.reasoning[:40] + "..." if len(result.reasoning) > 40 else result.reasoning
                print(
                    f"{caption_id:<12} {result.detected_tone:<12} "
                    f"{result.persona_boost:.2f}x   {result.tone_confidence:.2f}        {reasoning}"
                )
        else:
            print("No cached results found")
        return

    if args.clear:
        if cache.clear(args.creator, args.week):
            print(f"Deleted cache for {args.creator} / {args.week}")
        else:
            print("Cache does not exist")
        return

    parser.print_help()


if __name__ == "__main__":
    main()
